apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "flowers-sample-gpu"
  annotations:
    "autoscaling.knative.dev/target": "1"
    "serving.kubeflow.org/gke-accelerator": "nvidia-tesla-p100"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 6
    containerConcurrency: 1
    tensorflow:
      storageUri: "gs://kfserving-samples/models/tensorflow/flowers"
      runtimeVersion: "1.14.0-gpu"
      resources:
        limits:
          nvidia.com/gpu: 1